resource_group_name    = "rg-mango-qa"
app_service_plan_name  = "asp-mango-qa"
app_service_name       = "app-mango-qa"
storage_account_name   = "stmangodataqa"
storage_container_name = "mangocontainer"
sql_server_name        = "sqlmangoqa"
sql_database_name      = "sql-mango-qa"