name: Build Angular

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

  workflow_dispatch:

jobs:
  build-angular:
    name: Build Angular
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        environment:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup Node.js 16.x'
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: 'MangoAPI.Client/package-lock.json'

      - name: 'Setup Typescript 4.8'
        run: npm install -g typescript@4.8

      - name: 'Print current node version'
        run: node -v

      - name: 'Print current npm version'
        run: npm -v

      - name: 'Npm ci'
        working-directory: './MangoAPI.Client'
        run: npm ci

      - name: 'Install angular cli 15.2.2'
        run: npm install -g @angular/cli@15.2.2

      - name: 'Print current angular cli version'
        run: ng version

      - name: 'Compile TS files'
        working-directory: './MangoAPI.Client'
        run: tsc -p tsconfig.json

      - name: 'Angular build'
        working-directory: './MangoAPI.Client'
        run: ng build

      - name: 'Drop artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'angular-build-${{ matrix.environment }}'
          path: './MangoAPI.Presentation/wwwroot'
